### ISSUE TITLE
Não lê a planilha inteira

### ISSUE THREAD

**Issue by alexandrearume** [walterfcarvalho/advpl-xlsxtocsv#8]
O programa em C# entende que a primeira linha é o cabeçalho e não considera todas as colunas da planilha.
Por exemplo: Se na primeira linha eu tenho um título, ele irá ler somente a primeira coluna de todas as linhas da planilha.

**Comment by walterfcarvalho** [comment]
Oi tudo bem ? se quiser mandar para mim essa planilha desse layout posso dar uma olhada em porquê está dando erro apra você)  uma coisa que pegava muito era quando havia dados oculos na planilha (mas não sei se é o caso) ;)

**Comment by alexandrearume** [comment]
Olá Walter, tudo bem e você?
Segue uma planilha de exemplo.
[T003-Codigos_de_caracteristicas_nao_mensuraveis_20230201.xls](https://github.com/walterfcarvalho/advpl-xlsxtocsv/files/10678753/T003-Codigos_de_caracteristicas_nao_mensuraveis_20230201.xls)

**Comment by walterfcarvalho** [comment]
Olá, tudo bem ?  desculpe ter demorado estou meio atarefado, mas fiz testes com seu arquivo e foi tudo de boas, to anexando o video do processo. tem excel instalado na maquina ???[https://drive.google.com/file/d/1ZArHBZPzQenquSNK3owFNb4TjfD-Bu1C/view?usp=sharing](url)
espero que de certo

**Comment by alexandrearume** [comment]
Walter, perceba que na planilha tem a terceira coluna que a rotina não importou.

**Comment by alexandrearume** [comment]
Mas não teria como importar da maneira que está na planilha?

**Comment by walterfcarvalho** [comment]
Infelizmente não, pois essa conversão é uma chamada para o VBA do excel.

**Comment by walterfcarvalho** [comment]
na verdade pôde ser feito, veja no README.md como fazer.

**Comment by alexandrearume** [comment]
Certo. Vi que tem o parâmetro cSaltos. 
Na chamada do Shellexecute, qual é a posição do cSaltos? É a última onde esta o zero?
Shellexecute('open', '"' + GetClientDir() + cExe + '"', '"' + Alltrim(cArq) + '" "' + cIdPlan + '" "' + cDelimiter + '" ' , GetClientDir(), 0)

**Comment by walterfcarvalho** [comment]
a alteracao está feita pra poder chamar assim, na chamada da funcao:   
u_xlsxToArr(cArq, cIdPlan, cDelimiter, cSaltoLinhas) nao esqueça de atualizar o xlsxtocsv.exe na system.
